### ISSUE TITLE
Microsoft.AspNetCore.DataProtection.Redis uses StrongNamed redis package

### ISSUE THREAD

**Issue by Yantrio** [aspnet/DataProtection#245] opened 2017-06-08 11:16 UTC
This causes a hell of a lot of issues with other packages that use non-strongnamed assemblies.

Can we get a non-strongnamed redis based copy of Microsoft.AspNetCore.DataProtection.Redis so we dont need to all pull our hair out?

**Comment by davidfowl** [comment] 2017-06-08 11:22
It can't. All of our assemblies are themselves strong named and that's not going to change and we're not going to maintain 2 versions of packages.

**Comment by jchannon** [comment] 2017-06-08 11:23
So how do we handle it, what's MS official solution to this?

**Comment by Yantrio** [comment] 2017-06-08 11:26
I miss this version of @davidfowl :( https://github.com/octokit/octokit.net/issues/405#issuecomment-41655345

**Comment by mgravell** [comment] 2017-06-08 13:07
Oh nos, the strong-name debate.

There might be a simple solution here, although you might not like it:

- reality is that regardless of your views on strong names, "not having a strong name" is more of a technical barrier than "having a strong name"
- having two packages is a giant cluster-fail for everyone

As such, the conclusion we're reached is that *barring any sudden change of plan*, we will - in the next "major" revision, *break the identity*, such that:

- the currently non-strong-named package **becomes strong named**
- the currently strong-named package is retired - give or take whatever we need re `[TypeForwardedTo]` or whatever else

After a long and protracted battle, I think this is the only sensible option forward, and would apply to a few packages - SE.Redis, Dapper, etc.

I'm open to feedback, but I *don't* want another holy crusade of strong naming, so if you're going to argue the merits and detriments of strong names *themselves*; please, please, please don't. We all know what the battlefield looks like. We've all lost friends, colleagues and lovers to that blood-soaked wasteland.

**Comment by Yantrio** [comment] 2017-06-08 13:26
I think we aren't going to change the fact that strongnaming is here, and I'm happy to help other libraries (or fork if I need to) to get them onto a strong-named version of the Se.redis lib. I suppose it's up to the author of the libraries how they support strong name vs non strong name (2 libs like SE.redis or 1 lib thats just using strong named).

I think it may be worth making clear that the packages consuming SE.redis in this case, wouldn't have to move to be strongly named, but just switch from SE.redis to SE.redis.strongname.

**Comment by nosami** [comment] 2017-06-08 13:39
I used this https://github.com/dsplaisted/strongnamer... was easy to set up.

**Comment by jchannon** [comment] 2017-06-08 13:39
Why can't MS use this https://github.com/dsplaisted/strongnamer

**Comment by jchannon** [comment] 2017-06-08 13:40
Ooh snap @nosami :)

**Comment by davidfowl** [comment] 2017-06-08 16:25
@nosami @jchannon that's for package consumers, not producers. Luckily, if you're using .NET Core, there are no issues. The issue is .NET Framework and the only saving grace is the automatic binding redirects that the build system generates. 

Package authors realistically all need to be strong named and we (Microsoft) need to fix the .NET Framework to not require binding redirects to truly solve the problems that people hit (I'm fighting for this, again 😄).

**Comment by davidfowl** [comment] 2017-06-08 16:25
It's fine to have a bigger discussion about strong naming elsewhere but I'd prefer closing this issue and starting another issue on dotnet/corefx.

**Comment by nosami** [comment] 2017-06-08 16:26
I was talking about consumers - my comment was a suggestion for @jchannon :)

**Comment by jchannon** [comment] 2017-06-08 16:40
"Luckily, if you're using .NET Core, there are no issue". 

I didn't realise that lib was for consumers. Are you sure? The readme implies it's for when you want to strong name your app which we don't.

**Comment by nosami** [comment] 2017-06-08 16:57
StrongNamer allows you to easily have a mixture of strong named and non strong named assemblies in the same solution by strongly naming all your references at build time (it modifies the 3rd party assemblies and puts them into a subdirectory in the output folder and transparently modifies your references).

```
│   ├── obj
│   │   └── Debug
│   │       ├── MonoDevelop.FSharp.Tests.dll
│   │       ├── MonoDevelop.FSharp.Tests.dll.mdb
│   │       ├── MonoDevelop.FSharp.Tests.fsproj.CoreCompileInputs.cache
│   │       ├── MonoDevelop.FSharp.Tests.fsproj.FileListAbsolute.txt
│   │       ├── MonoDevelop.FSharp.Tests.fsprojResolveAssemblyReference.cache
│   │       └── SignedAssemblies
│   │           ├── ExtCore.dll
│   │           ├── FSharp.Compiler.Service.MSBuild.v12.dll
│   │           ├── FSharp.Compiler.Service.dll
│   │           └── MonoDevelop.FSharp.Shared.dll
```

**Comment by davidfowl** [comment] 2017-06-08 17:31
> I didn't realise that lib was for consumers. Are you sure? The readme implies it's for when you want to strong name your app which we don't.

Binding redirects don't exist on .NET Core. There's nothing that makes you strong name your application by default, what's the problem you're seeing?

**Comment by jchannon** [comment] 2017-06-08 17:46
Repro here - https://github.com/jchannon/strongnaming

Two references: `Microsoft.AspNetCore.DataProtection.Redis` & `Serilog.Sinks.Redis.List` the latter references a non strong name Redis lib.

Try and run the app that references a type in Redis and boom

```
Program.cs(10,27): error CS0433: The type 'ConfigurationOptions' exists in both 'StackExchange.Redis.StrongName, Version=1.1.605.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=1.1.608.0, Culture=neutral, PublicKeyToken=null' [/Users/jonathan/Projects/strongnaming/strongnaming.csproj]

The build failed. Please fix the build errors and run again.
```

**Comment by mgravell** [comment] 2017-06-08 17:48
That sounds like that awkward area where "extern alias" becomes useful, but
it again emphasises how much pain is introduced by dual libs :(

Sorry, all I can do is fix it in the future hypothetical tense, by killing
one of the twins.

**Comment by davidfowl** [comment] 2017-06-08 17:49
@mgravell it's time...

**Comment by jchannon** [comment] 2017-06-08 17:50
Can I confirm that if you didn't have the Regis.Strongname package and MS references a non strong version but then they strong named their libs all would be well?

**Comment by davidfowl** [comment] 2017-06-08 17:50
@jchannon yea that's screwed.

**Comment by terrajobst** [comment] 2017-06-08 18:18
As far as I'm concerned I'd just second what @mgravell [said above](https://github.com/aspnet/DataProtection/issues/245#issuecomment-307097403).

I'm with @davidfowl (holy cow, I'm sensing this might be used against me at some point 😄): we need fix .NET Framework to make automatic binding redirects the default. Ideally, this should happen at runtime.

**Comment by PureKrome** [comment] 2017-06-09 03:44
If (when?) this issue gets raised in `dotnet/corefx` can someone kindly post a link in here, plz?

**Comment by blowdart** [comment] 2017-06-09 17:00
As this is only tangentially data protection related closing the issue.

**Closed by blowdart** 2017-06-09 17:00 UTC

**Comment by sandorfr** [comment] 2017-12-16 01:26
> Sorry, all I can do is fix it in the future hypothetical tense, by killing
one of the twins.

Please do :) so that other libraries which relies on your package use the same as .net core team :)
