### ISSUE TITLE
Storing data protection keys file in another storage systems

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/DataProtection#104] opened 2015-11-13 14:09 UTC
> From https://twitter.com/PinpointTownes/status/665165343879491585

Is there any samples to store the data protection keys file in another storage systems like Azure vault, azure storage, AWS S3, etc.?

**Comment by tugberkugurlu** [comment] 2015-11-13 14:16
I can see that there is already an issue for this: https://github.com/aspnet/DataProtection/issues/92

**Comment by blowdart** [comment] 2015-11-13 14:20
Closed as dupe of #92

**Closed by blowdart** 2015-11-13 14:20 UTC
