### ISSUE TITLE
System.FormatException in LoggingExtensions

### ISSUE THREAD

**Issue by NatMarchand** [aspnet/DataProtection#129] opened 2016-03-16 15:35 UTC
### Title
When logging level is Debug, calling XmlKeyManager.ProcessKeyElement(XElement keyElement) will cause a `System.FormatException: Input string was not in a correct format.` exception

### Functional impact
Unable to use DataProtection API (and therefore any authentication)

### Minimal repro steps
dnx451 with dnx 1.0.0-rc2-20213 clr x86 win
All AspNetCore assemblies are 1.0.0-rc2-20230 (from aspnetcidev)
Project is available : https://github.com/NatMarchand/FormatExceptionRepro
Using MVC + OpenIdConnect authentication
When navigating to a restricted uri (with [Authorize] on controller or method)
LogLevel = Debug (works correctly in LogLevel = Information)

### Expected result
No exception (and logging "found key")

### Actual result
Error 500 :
System.Format exception : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

### Further technical details
```
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.Diagnostics.Debug.WriteLine(String format, Object[] args)
   at Microsoft.Extensions.Logging.Debug.DebugLogger.DebugWriteLine(String message, String name)
   at Microsoft.Extensions.Logging.Debug.DebugLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_01.<Define>b__0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggingExtensions.FoundKey(ILogger logger, Guid keyId)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.ProcessKeyElement(XElement keyElement)
```

**Comment by bbehrens** [comment] 2016-03-16 18:21
We ran into this exact issue I think, although we're using CookieAuthentication.  The problem is here:

https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/LoggingExtensions.cs#L372

The GUID is formatted with the `:B` switch which results in putting braces around the GUID.  Eventually this ends up in a call to System.Diagnostics.Debug.WriteLine(message, name).  Message has the curly braces in it around the GUID and it blows up here because it can't format the string.

**Comment by soeron** [comment] 2016-03-19 17:41
+1 having this issue too.

**Comment by blowdart** [comment] 2016-03-23 03:46
@Eilon please allocate as you see fit.

**Comment by Eilon** [comment] 2016-03-23 05:09
@muratg 's team. But if no one available, I can find someone ASAP.

**Comment by muratg** [comment] 2016-03-23 15:40
Assigned to @BrennanConroy.  We should add a test case as well.

**Comment by BrennanConroy** [comment] 2016-03-23 21:37
Fixing in ad487c76e16e52474572694d98feafd78575318d
Will close when it goes through the CI

**Closed** 2016-03-25 18:58 UTC
Labels: 3 - Done, bug
