### ISSUE TITLE
Delay on first request due to key encryption at rest

### ISSUE THREAD

**Issue by Eilon** [aspnet/DataProtection#193] opened 2016-12-14 22:20 UTC
_From @shravan2x on December 11, 2016 8:51_

I have an Asp.NET Core 1.1 MVC app. On every run on the app, it stalls for 3 seconds just before this is printed:

```
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\name\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
```

I don't mind the log itself, but what causes the delay? Is this a bug?

_Copied from original issue: aspnet/Mvc#5613_

**Comment by Eilon** [comment] 2016-12-14 22:20
@blowdart should this bug move to the https://github.com/aspnet/DataProtection/ repo?

**Comment by Eilon** [comment] 2016-12-14 22:20
_From @blowdart on December 14, 2016 22:12_

Maybe. I'm not sure I would consider it a bug to be honest, the first request is always going to block until we get a key ring open.

**Comment by blowdart** [comment] 2016-12-14 22:22
That long a delay is a little weird though.

**Comment by shravan2x** [comment] 2016-12-15 05:08
Thanks for moving this. It always takes at least 3s. Sometimes even more.

**Comment by natemcmaster** [comment] 2017-05-02 23:34
@shravan2x can you share more code to help repro the issue? A minimal repro that isolates the issue to just DataProtection APIs is ideal. MVC adds a lot of overhead. But if that's too much work, can you share your Startup.cs file?

Btw, if your only usage is calling `.AddDataProtection()` in Startup, then I'd guess the delay is the collective time it takes to wire up services, controllers, loggers, etc., not to mention time the runtime takes to JIT all that code. It just so happens that most of the logging in an ASP.NET Core MVC app doesn't happen until after that is done, and this particular log message happens in the middle of service discovery.

**Comment by shravan2x** [comment] 2017-05-03 05:57
@natemcmaster You can find my Startup.cs [here](https://gist.github.com/shravan2x/0fe4d5a0b345eea0a939ac0b650e88a1). I have removed some instance objects unrelated to MVC or anything else.

I used to have this problem with all my projects, but only some continue to. I believe this is because I aggressively removed packages that I didn't think were important. I have never intentionally setup data protection. It probably came along with MVC or so.

I would love to compare some of my projects with+without the issue and try to corner the cause myself, but this is finals week and I won't be able to until long past the 2.0 release on May 10th =/.

**Comment by natemcmaster** [comment] 2017-05-04 17:15
@shravan2x thanks for sharing the code. There doesn't appear to be anything wrong. Mvc pulls in the Microsoft.AspNetCore.Antiforgery package, which relies on DataProtection, which is why you are seeing this message even though you never intentionally set up data protection.

Can you clarify something else for me? You said before, "On every run on the app, it stalls for 3 seconds just before this is printed". What is the "begin" event you are referring to? Launching in Visual Studio? An actual HTTP request hitting a controller? Or do you mean you see a delay between `dotnet run` and the appearance of the DataProtectionServices console message?

**Comment by shravan2x** [comment] 2017-05-04 20:00
The issue occurs when the app is run, _how it is started_ does not seem to matter. Launching in Visual Studio and `dotnet run` both have the delay. This delay is not initially apparent, the app starts up and display the standard 4 lines with address, port, etc correctly.

The delay occurs when the first request is made. No standard log messages are visible until the 3s delay completes. After this, everything works as normal. If other requests are made after the initial request but before the delay completes, the other requests are pipelined behind the first (In a few cases, I have also received weird errors when this happened). So every time I deploy an ASP application, I manually send the first request so _users_ don't face the delay.

I have only noticed this issue when the requests are handled by MVC. Requests I make to to custom handlers or even `StaticFiles` don't have the delay. I'm not too sure if this last statement is correct though.

**Comment by natemcmaster** [comment] 2017-05-04 20:22
Good to know. That rules out lots of possibilities. Would you be able to provide data from CPU profiling to on where your app is spending time? To narrow this down, it would be best to starting profiling after the app launches and ending after the first request finishes.

**Comment by shravan2x** [comment] 2017-05-05 22:04
Sorry, not the next few days at least.

**Comment by natemcmaster** [comment] 2017-05-05 22:07
@shravan2x Good luck on finals :)

**Comment by natemcmaster** [comment] 2017-06-06 17:25
I'm closing for now as we don't have enough data to investigate this bug further. If you are able to gather profiling data, we can re-open for more investigation.

That said, I added a feature last week that should reduce delay on first request. The startup filter added in #241 pre-loads the key ring before the server starts accepting requests. This will be in 2.0.0-preview3 nightly bits and should be in 2.0.0 RTM. If it doesn't solve your issue, please let me know.

**Closed by natemcmaster** 2017-06-06 17:25 UTC
Labels: 1 - Ready, Investigate

**Comment by shravan2x** [comment] 2017-10-05 00:27
Updating after testing on .NET Core 2.0 and a completely different computer. The issue still exists. First requests take around 3 times as long as following ones on the default ASP.NET Core 2.0 MVC template.

I tried to gather performance profiling data, but these components are severely broken on VS2017 and do not even start.
